name: build image

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: install buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push image to registry
        run: |
          docker buildx build --push \
            --target production \
            --tag ${{ secrets.REGISTRY }}/api-sensores:latest \
            --platform linux/amd64,linux/arm64 ./sensores-api
